### ISSUE TITLE
Pupil displacement

### ISSUE THREAD

**Issue by thayerAlshaabi** [advancedbioimagingcenter/opticalaberrations#1]
Save pupil displacement as a `.tif` file

**Comment by dmilkie** [comment]
The image that gets output.  I'm not able to read it from LabVIEW, and ImageJ wants to use the Bio-Formats reader.  Is it a plain vanilla .tif or something like BigTIFF or compressed weirdly?

**Comment by dmilkie** [comment]
Looks like it's getting saved as a **64-**bit image.  Tiff's can only be 32-bit floating point.  Try that.
